### ISSUE TITLE
Stoplinks incorrect at Zwolle centraal

### ISSUE THREAD

**Issue by IgoBoerrigter** [plannerstack/map-data-issues#2]
## 1. Description:

Stoplinks between platforms at Zwolle central are missing or incorrect. 
## 2. Impact

Transfers between train result in unnecessary long trips
## 3. Image

![zwolle](https://cloud.githubusercontent.com/assets/10044515/10486015/4e20bdb0-728d-11e5-819d-9fe16b2dae56.png)
## 4. Reproduction

Create a trip with a transfer at zwolle centraal: Meppel >> Olst
OTP advises to take a bus between transfers on the same station:
## 5. Example URL

[Trip url](http://demo.planner.plannerstack.com/?module=planner&fromPlace=52.692576696575685%2C6.198263168334961&toPlace=52.33586352768354%2C6.11363410949707&time=1%3A30pm&date=10-14-2015&mode=TRANSIT%2CWALK&maxWalkDistance=750&arriveBy=false&wheelchair=false&locale=en&itinIndex=0)

**Comment by sven4all** [comment]
Made this change:
https://www.openstreetmap.org/changeset/34630541

Tunnel was in maintenance and therefore not accessible, setted tunnel on available again and added a stair to platform 9-10.
http://nos.nl/artikel/2043548-vier-jaar-en-3-2-miljoen-tegeltjes-verder-spoortunnel-zwolle-open.html

**Comment by sven4all** [comment]
Resolved

![schermafbeelding 2015-10-18 om 20 29 13](https://github-cloud.s3.amazonaws.com/assets/2699483/10565675/0c19e3d6-75d7-11e5-9ed7-7872e8344983.png)
