### ISSUE TITLE
Stairs missing in Heerenveen 

### ISSUE THREAD

**Issue by JesseC42** [plannerstack/map-data-issues#72]
## 1. Description:

In Heerenveen some stairs close to the station are missing which leads to unnecessary walking. Also, the platforms are not connected. 
## 2. Impact

Extra walking, while there are stairs.
## 3. Image

![schermafbeelding 2015-11-16 om 15 00 52](https://cloud.githubusercontent.com/assets/15247075/11183615/1ea07c9c-8c73-11e5-9de1-09186fa90ba3.png)
![schermafbeelding 2015-11-16 om 15 00 41](https://cloud.githubusercontent.com/assets/15247075/11183616/1ece7c32-8c73-11e5-8dae-a3de0ffb9156.png)
## 4. Reproduction

Create a route from Zwolle to Heerenveen and set the final destination just east of the station.
## 5. Example URL

[Zwolle - Heerenveen](http://demo.planner.plannerstack.org/?module=planner&fromPlace=52.50274316522345%2C6.100502014160156&toPlace=52.959839331598154%2C5.914410352706909&time=5%3A10pm&date=11-13-2015&mode=TRANSIT%2CWALK&maxWalkDistance=750&arriveBy=false&wheelchair=false&showIntermediateStops=false&locale=en&itinIndex=0)

**Comment by JesseC42** [comment]
The stairs are visible and the walking route is now working in OTP/OSM. 

![schermafbeelding 2015-11-25 om 10 07 48](https://cloud.githubusercontent.com/assets/15247075/11392894/eb20cd72-935c-11e5-92e1-9c6576e0f99c.png)

**Comment by martiensch** [comment]
trappen van tunnel toegevoegd

**Comment by JesseC42** [comment]
Hi @martiensch beetje laat maar alsnog bedankt voor je aanpassingen bij de stations! Cool!

**Comment by JesseC42** [comment]
![schermafbeelding 2017-01-23 om 12 12 13](https://cloud.githubusercontent.com/assets/15247075/22201739/38401cfa-e165-11e6-88f0-6fdd7900b21a.png)
Fixed!
