### ISSUE TITLE
Stoplink issue Groningen Europapark

### ISSUE THREAD

**Issue by JesseC42** [plannerstack/map-data-issues#74]
## 1. Description

The stop linkers for station Groningen Europapark are in the wrong position. They are about 200meters from the original place. 
## 2. Impact

Lots of extra walking required. Travelers might start walking in a direction which is not needed. Confusion can arise.
## 3. Image

![schermafbeelding 2015-11-17 om 12 34 14](https://cloud.githubusercontent.com/assets/15247075/11210306/96566224-8d27-11e5-8a33-b45fa0a6bd5b.png)
## 4. Reproduction

Create a route from Groningen CS to Groningen Europapark and set the destination close to the icon of the station.
## 5. Example URL

[Groningen Europapark](http://demo.planner.plannerstack.org/?module=planner&fromPlace=53.21117298038268%2C6.5640950202941895&toPlace=53.20355850041445%2C6.585831642150879&time=5%3A10pm&date=11-13-2015&mode=TRANSIT%2CWALK&maxWalkDistance=750&arriveBy=false&wheelchair=false&showIntermediateStops=false&locale=en&itinIndex=0)

**Comment by martiensch** [comment]
Layout van het station bijgewerkt mbv actuele luchtfoto's van cyclomedia

**Comment by JesseC42** [comment]
The incorrect latlong is in the GTFS data: 53.2062092641,6.58257544041

![schermafbeelding 2016-02-15 om 17 16 22](https://cloud.githubusercontent.com/assets/15247075/13054093/27a756da-d408-11e5-8f18-cb534b26090c.png)

**Comment by JesseC42** [comment]
![schermafbeelding 2017-01-23 om 12 07 55](https://cloud.githubusercontent.com/assets/15247075/22201621/9b525b88-e164-11e6-8a9a-910a7da018a7.png)
The polyline is still incorrect, however this does not have any influence on the trip. The stop and walking are now correct.
