### ISSUE TITLE
Location Nijmegen Lent

### ISSUE THREAD

**Issue by JesseC42** [plannerstack/map-data-issues#79]
## 1. Description

The stop linkers seem to be a little bit far north and the new exits are more south. Also, it is possible to reach the final destination directly instead of walking around. The station is updated not that long ago, but in OTP not adjusted yet. Because of the long walking the main options that are suggested are bus trips. however they take much longer. 
## 2. Impact

Longer routes when taking a bus or confusion when asked to walk so much.
## 3. Image

![schermafbeelding 2015-12-04 om 16 13 06](https://cloud.githubusercontent.com/assets/15247075/11593012/3c337df8-9aa2-11e5-9103-70b5b9ccedbb.png)
## 4. Reproduction

Create a route from Nijmegen Station to Nijmegen Lent.
## 5. Example URL

[Nijmegen Lent](http://demo.planner.plannerstack.org/?module=planner&fromPlace=51.84305616282461%2C5.8525049686431885&toPlace=51.86212221626927%2C5.860927104949951&time=4%3A05pm&date=12-04-2015&mode=TRANSIT%2CWALK&maxWalkDistance=750&arriveBy=false&wheelchair=false&showIntermediateStops=false&locale=en&itinIndex=0)

**Comment by pieterbuzing** [comment]
It looks better now. @JesseC42 can we close this issue?
![nijmegen-lent](https://cloud.githubusercontent.com/assets/9744935/15361242/fca9be76-1d10-11e6-8a28-2e3e5522aa64.png)

**Comment by JesseC42** [comment]
It does look much better now @pieterbuzing. However, I found that many times the bus is still the preferable option [Nijmegen-Lent](http://planner.plannerstack.com/?module=planner&fromPlace=51.843255016320775%2C5.852322578430176&toPlace=51.86221166254757%2C5.8599454164505005&time=10%3A31am&date=05-19-2016&mode=TRANSIT%2CWALK&maxWalkDistance=750&arriveBy=false&wheelchair=false&locale=en&itinIndex=1) when the end position is close to the station even though these trips are longer when taking the train. I think this is a problem of walking permissions of some paths nearby. I changed this, so hopefully this will fix it and than we can close it. Thanks for your help and effort.

**Comment by JesseC42** [comment]
We can now close this one @pieterbuzing. After the latest update the paths are recognized and used so now only train routes are given which makes much more sense:

![schermafbeelding 2016-06-01 om 16 08 27](https://cloud.githubusercontent.com/assets/15247075/15712573/1f51b732-2813-11e6-9c7b-03a442cc739b.png)
